### PR TITLE
Implemented Visitor Pattern

### PR DESCRIPTION
**Pull request by Lewis-Allen**

### CODE REVIEW

**Review by Gerome — COMMENTED** [review]
Receiving the following error.

>Your project does not reference ".NETFramework,Version=v4.6.1" framework. Add a reference to ".NETFramework,Version=v4.6.1" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.

**Comment by Lewis-Allen** [comment]
Did you delete the old branch and reclone the thing entirely?

**Comment by Gerome** [comment]
Yes and it still doesnt work.

**Comment by Lewis-Allen** [comment]
Works fine here. Will try on a different PC.

**Comment by Lewis-Allen** [comment]
Works fine on other PC. Maybe try a different cloning location?

**Comment by Gerome** [comment]
Issue was solved by deleting and recloning

**Review by Gerome — APPROVED** [review]

**Pull request merged**
